<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Install Logs</title>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'));
        ?>
    </head>
    <body>
        <header>
            <div class="container">
                <a href="/">Install Logs</a>
            </div>
        </header>
        <main>
            <?= $this->content ?>
        </main>
        <footer>
            <div class="container">
                &copy; 2017 Install Logs, Inc.
            </div>
        </footer>
    </body>
</html>
