<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Install Logs</title>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <link href="/css/style.css?v=2017091101" media="screen" rel="stylesheet" type="text/css">
        <link href="/favicon.ico" rel="shortcut icon">
    </head>
    <body>
        <header>
            <div class="container">
                <a href="/">Install Logs</a>
            </div>
        </header>
        <main>
            <div class="main-container">
                <?= $this->content ?>
            </div>
        </main>
        <footer>
            <div class="container">
                &copy; 2017 Install Logs, Inc.
            </div>
        </footer>
    </body>
</html>
