<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Install Logs</title>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'));
        ?>

        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
        ?>
    </head>
    <body>
        <?= $this->content ?>
    </body>
</html>
