<?php
$lineHrefHelper = $this->lineHref();
?>
<h1>Welcome</h1>

<p><b>Install Logs</b> documents and links to every line of various install logs. Users can then comment on individual lines, asking questions about their meaning or offering useful feedback for other system administrators.</p>

<ol>
<?php foreach ($newestLines as $line): ?>
    <?php $href = $lineHrefHelper->getHref($line); ?>
    <li><a href="<?= $this->escape($href); ?>"><?= $this->escape($line->string); ?></a></li>
<?php endforeach ?>
</ol>
